### ISSUE TITLE
Please bump my access rights up a notch or two

### ISSUE THREAD

**Issue by petecooper** [textpattern/server-config#72]
I'd like to tweak some repo settings, but I don't have the appropriate rights. Please could someone elevate my account to the next stage up (whatever that is that allows settings to be tweaked). Thanks!

**Comment by philwareham** [comment]
Hey! I’m currently at centre parcs with only mobile, so if you are happy to wait until Monday that’s cool. Otherwise maybe Stef can update your settings.

Philip Wareham | Technical Director



30 St. Georges Road, Badshot Lea, Farnham, Surrey GU9 9LX, United Kingdom
Office: 01252 734144
Mobile: 07971 668332
Website: www.designhive.com

**Comment by Bloke** [comment]
*scratches head*

![Screenshot 2022-05-23 at 23 18 22](https://user-images.githubusercontent.com/21252/169914056-e51919d3-0db0-49a0-956e-e0b4cfa627ac.png)

**Comment by Bloke** [comment]
Seems all three of us have the same Write access. Maybe we should bump the Team permissions up to Maintain or Admin?

Or am I looking in the wrong place...?

**Comment by petecooper** [comment]
No idea! For whatever reason, I don't have the settings gear / cog thingy, which is what I'd like access to.

**Comment by Bloke** [comment]
I've bumped the team up a grade to Maintain. Any change?

**Comment by petecooper** [comment]
Cheers @Bloke!
